name: Tests

on:
  push:
    branches: [main]
  pull_request:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  unit-tests:
    runs-on: ubuntu-latest
    container: silex/emacs:${{ matrix.emacs_version }}-ci
    timeout-minutes: 5
    strategy:
      fail-fast: false
      matrix:
        emacs_version:
          - "30.2"
    steps:
      - uses: actions/checkout@v5

      - run: emacs --batch -l scripts/bootstrap-elpaish.el

      - env:
          ELPAISH_SIGNING_KEY: "__testing_value"
          ELPAISH_GPG_PASSPHRASE: ""
        run: |
          emacs --batch -L pkg -L scripts -L test \
            -l test/test-elpaish.el \
            --eval '(ert-run-tests-batch-and-exit "^elpaish-test-.*")'
